#+TITLE: Dotfiles.w0lper	
#+AUTHOR: Vinicius Moraes
#+EMAIL: vinicius.moraes@eternodevir.com
#+OPTIONS:   num:nil

This repository contains my personal collection of scripts and configuration files, stored in the standard repository path =~/.config/dotfiles/=, with symbolic links pointing from =~=.

** Requirements

Before using my dotfiles, please ensure that your user's =$PATH= includes =~/.local/bin/=, and your =~/.bashrc= file includes =~/.bash_aliases=.

** Scripts

The following scripts are included in this repository:

- VPN status and city
- Network status
- RAM usage
- CPU usage
- Battery status
- Volume status
- Volume control
- Weather status
- Date and time
- Qbit kill switch
- Power menu*

Additionally, this repository includes an autostart script for *dwm*.

The scripts are located in the following repository paths: =~/.local/bin/=, =~/.local/share/dwm/=.

** Configuration

This repository includes configuration files for the following applications:

- CLI aliases
- Xresources
- Urxvt
- Tmux
- Sxhkd
- Kmonad

The configuration files are located in the following repository paths: =.=, =~/.config/=.

** Automating symbolic links

To automate the process of creating symbolic links from the repository files to their respective locations, you can use the following:

#+begin_src shell
  #!/bin/bash

  mkdir -p ~/.local/ &
  mkdir -p ~/.local/share/ & 
  mkdir -p ~/.config/tmux/ &
  mkdir -p ~/.config/sxhkd/ &
  mkdir -p ~/.config/kmonad/ &

  sleep 3

  ln -sf ~/.config/dotfiles/.local/bin/ ~/.local/bin &
  ln -sf ~/.config/dotfiles/.local/share/dwm/ ~/.local/share/dwm &
  ln -sf ~/.config/dotfiles/.config/tmux/tmux.conf ~/.config/tmux/tmux.conf &
  ln -sf ~/.config/dotfiles/.config/kmonad/config.kbd ~/.config/kmonad/config.kbd &
  ln -sf ~/.config/dotfiles/.config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc &
  ln -sf ~/.config/dotfiles/.Xresources ~/.Xresources &
  ln -sf ~/.config/dotfiles/.bash_aliases ~/.bash_aliases &
  ln -sf ~/.config/dotfiles/.config/urxvt/ ~/.urxvt &

#+end_src

If you use *GNU Emacs*, you can execute the above code block with =C-c C-c=. Otherwise, save and run it as a shell script.

** License

 This project is licensed under the GNU General Public License v3.0 (GPL-3.0), unless an exception is made explicit in context. The GPL is a copyleft license that guarantees the freedom to use, modify, and distribute software. It ensures that users have control over the software they use and promotes collaboration and sharing of knowledge. By requiring that derivative works of GPL-licensed software also be licensed under the GPL, the license ensures that the freedoms it provides are extended to future generations of users and developers. Please see the =LICENSE= file for more information.
