#+TITLE: Dotfiles.w0lper	
#+AUTHOR: Vinicius Moraes
#+EMAIL: vinicius.moraes@eternodevir.com
#+OPTIONS:   num:nil

This repository contains my personal collection of scripts and configuration files, stored in the standard repository path =~/.config/dotfiles/=, with symbolic links pointing from =~=.

**** Table of contents                                             :TOC_4:
  - [[#requirements][Requirements]]
  - [[#scripts][Scripts]]
  - [[#configurations][Configurations]]
  - [[#usage][Usage]]
    - [[#automating-symbolic-links][Automating symbolic links]]
  - [[#license][License]]

** Requirements

Before using my dotfiles, ensure that user's =$PATH= includes =~/.local/bin/=, and =~/.bashrc= includes =~/.bash_aliases=.

** Scripts

The following scripts are included in this repository:

- VPN status and city
- Network status
- RAM usage
- CPU usage
- Battery status
- Volume status
- Volume control
- Weather status
- Date and time
- Qbit kill switch
- Power menu*
- Dwm autostart
- Global dark/light mode switcher

The scripts are located in the following repository paths: =~/.local/bin/=, =~/.local/share/dwm/=.

** Configurations

This repository includes configuration files for the following applications:

- CLI aliases
- Xresources
- Urxvt
- Tmux
- Sxhkd
- Kmonad
- Xsettingsd

The configuration files are located in the following repository paths: =.=, =~/.config/=.

** Usage
*** Automating symbolic links

To automate the process of creating symbolic links from the repository files to their respective locations, use the following script:

#+begin_src shell
  #!/bin/bash

  mkdir -p "${HOME}/.local/bin/" &
  mkdir -p "${HOME}/.local/share/" & 
  mkdir -p "${HOME}/.config/tmux/" &
  mkdir -p "${HOME}/.config/sxhkd/" &
  mkdir -p "${HOME}/.config/kmonad/" &
  mkdir -p "${HOME}/.config/xsettingsd/" &

  sleep 3

  ln -sf "${HOME}/.config/dotfiles/.local/bin/" "${HOME}/.local/bin/" &
  ln -sf "${HOME}/.config/dotfiles/.local/share/dwm/" "${HOME}/.local/share/dwm/" &
  ln -sf "${HOME}/.config/dotfiles/.config/tmux/tmux.conf" "${HOME}/.config/tmux/tmux.conf" &
  ln -sf "${HOME}/.config/dotfiles/.config/kmonad/config.kbd" "${HOME}/.config/kmonad/config.kbd" &
  ln -sf "${HOME}/.config/dotfiles/.config/sxhkd/sxhkdrc" "${HOME}/.config/sxhkd/sxhkdrc" &
  ln -sf "${HOME}/.config/dotfiles/.config/xsettingsd/xsettingsd-dark.conf" "${HOME}/.config/xsettingsd/xsettingsd.conf" &
  ln -sf "${HOME}/.config/dotfiles/.Xresources-dark" "${HOME}/.Xresources" &
  ln -sf "${HOME}/.config/dotfiles/.bash_aliases" "${HOME}/.bash_aliases" &
  ln -sf "${HOME}/.config/dotfiles/.config/urxvt/" "${HOME}/.urxvt" &
#+end_src

#+RESULTS:

If you use *GNU Emacs*, you can execute the above code block with =C-c C-c=.

** License

This project is licensed under the GNU General Public License v3.0 (GPL-3.0), unless an exception is made explicit in context. The GPL is a copyleft license that guarantees the freedom to use, modify, and distribute software. It ensures that users have control over the software they use and promotes collaboration and sharing of knowledge. By requiring that derivative works of GPL-licensed software also be licensed under the GPL, the license ensures that the freedoms it provides are extended to future generations of users and developers.

See the =LICENSE= file for more information.
